#!/usr/bin/env bash
# Generates docs/platform/SCHEMA.md from a database that has all migrations applied.
# Usage: PGHOST=… PGPORT=… PGUSER=… DBNAME=bgiff_ci supabase/scripts/gen-schema-doc.sh > docs/platform/SCHEMA.md
set -euo pipefail
DBNAME="${DBNAME:-bgiff_ci}"
Q() { psql -X -At -d "$DBNAME" -c "$1"; }

cat <<'HDR'
# BGIFF Platform — Database Schema (generated)

Generated by `supabase/scripts/gen-schema-doc.sh` from the migrations in `supabase/migrations/` applied to a clean Postgres 16.
Do not edit by hand: change a migration, run `npm run db:check`, then regenerate.

Conventions: `public` schema of the dedicated Supabase project · UUID keys · integer cents · `timestamptz` (UTC) · `deleted_at` soft delete on business tables · `audit_log` append-only · RLS enabled on **every** table (default deny) · service_role only from the server after `decideAccess()`.

Migration files (forward, with a matching `down/` file each):

HDR
for f in supabase/migrations/*.sql; do
  b=$(basename "$f")
  head1=$(sed -n '1p' "$f" | sed 's/^-- //')
  status=$(grep -m1 'STATUS: DRAFT' "$f" | sed 's/^-- //' || true)
  echo "- \`$b\` — $head1${status:+ — **$status**}"
done

cat <<'MID'

Consent kinds ([C-1]): `screening_licence` · `gates_rules` · `marketing` — three separate acts, each with `text_version` + frozen `text_snapshot`.

## Enum types

MID
Q "select '- \`' || t.typname || '\` = ' || string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
   from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
   where n.nspname = 'public' group by t.typname order by t.typname;"

echo
echo "## Tables"
echo
for t in $(Q "select tablename from pg_tables where schemaname='public' order by tablename"); do
  echo "### \`$t\`"
  echo
  desc=$(grep -h -B1 "^create table $t (" supabase/migrations/*.sql | grep '^--' | sed 's/^-- //' | head -1 || true)
  [[ -n "$desc" ]] && echo "$desc" && echo
  echo "| column | type | null | default / notes |"
  echo "|---|---|---|---|"
  Q "select '| \`' || column_name || '\` | ' || replace(data_type, 'character varying', 'varchar') ||
        case when udt_name not in ('int4','int8','text','bool','uuid','timestamptz','jsonb','bytea','numeric','citext','tsvector','date','_text') and data_type = 'USER-DEFINED' then ' (' || udt_name || ')' when data_type = 'ARRAY' then ' ' || udt_name else '' end ||
        ' | ' || case is_nullable when 'YES' then '✓' else '' end || ' | ' || coalesce(replace(column_default, '|', '\|'), '') ||
        case when is_generated = 'ALWAYS' then 'generated' else '' end || ' |'
     from information_schema.columns where table_schema='public' and table_name='$t' order by ordinal_position;"
  echo
  keys=$(Q "select '- ' || conname || ': ' || pg_get_constraintdef(oid) from pg_constraint where conrelid = '$t'::regclass and contype in ('p','f','u','c') order by contype, conname;")
  [[ -n "$keys" ]] && echo "Keys & constraints:" && echo && echo "$keys" && echo
  idx=$(Q "select '- ' || indexname || ': ' || regexp_replace(indexdef, '^CREATE (UNIQUE )?INDEX \S+ ON public\.\S+ ', '\1') from pg_indexes where schemaname='public' and tablename='$t' and indexname not in (select conname from pg_constraint where conrelid='$t'::regclass) order by indexname;")
  [[ -n "$idx" ]] && echo "Indexes:" && echo && echo "$idx" && echo
  trg=$(Q "select '- ' || tgname || ' → ' || p.proname || '()' from pg_trigger tg join pg_proc p on p.oid = tg.tgfoid where tgrelid='$t'::regclass and not tgisinternal order by tgname;")
  [[ -n "$trg" ]] && echo "Triggers:" && echo && echo "$trg" && echo
  pol=$(Q "select '- **' || policyname || '** (' || cmd || ', ' || array_to_string(roles, ',') || '): ' || regexp_replace(coalesce(qual, 'n/a'), '\s+', ' ', 'g') || case when with_check is not null and with_check <> coalesce(qual,'') then ' · check: ' || regexp_replace(with_check, '\s+', ' ', 'g') else '' end from pg_policies where schemaname='public' and tablename='$t' order by policyname;")
  echo "RLS policies:"
  echo
  if [[ -n "$pol" ]]; then echo "$pol"; else echo "- (none besides admin_all → effectively founder/admin + service role only)"; fi
  echo
done

echo "## Views"
echo
Q "select '- \`' || viewname || '\` (security_invoker): ' || regexp_replace(definition, '\s+', ' ', 'g') from pg_views where schemaname='public' order by viewname;"
echo
echo "## Functions"
echo
Q "select '- \`' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')\` → ' || pg_get_function_result(p.oid) || case when p.prosecdef then ' · security definer' else '' end
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname='public' order by p.proname;"
